"""add foreign key to review

Revision ID: 60471d414adf
Revises: 9dc1b7c1e73c
Create Date: 2025-06-16 10:33:38.902780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60471d414adf'
down_revision = '9dc1b7c1e73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'reviews', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
